
import { Geist, Geist_Mono } from "next/font/google";
import "../styles/globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';
import { AppWrapper } from "./AppWrapper";

// Load fonts in module scope
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const fontsClassName = `${geistSans.variable} ${geistMono.variable} antialiased`

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={fontsClassName}>
      <body>
        <AppWrapper>
          {children}
        </AppWrapper>
      </body>
    </html>
  );
}
