import "@/app/styles/globals.css";
import type {Metadata} from "next";

import 'bootstrap/dist/css/bootstrap.min.css';
import AuthWrapper from './AuthWrapper';
import AppWrapper from './AppWrapper';
import Image from "next/image";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};
import {setupAmplify} from "@/app/utils/cognito";

setupAmplify();

export default function Layout({children}: { children: React.ReactNode }) {
    return (
        <html lang="en">
        <body>
        <div style={{
            position: "fixed",
            top: 0,
            bottom: 0,
            left: 0,
            width: "60px",
            zIndex: 0,
            pointerEvents: "none",
        }}>
            <Image
                src="/left.png"
                alt="left decoration"
                fill
                style={{ objectFit: 'cover', objectPosition: 'top left'}}
            />
        </div>
        <div style={{
            position: "fixed",
            top: 0,
            bottom: 0,
            right: 0,
            width: "60px",
            zIndex: 0,
            pointerEvents: "none"
        }}>
            <Image
                src="/right.png"
                alt="right decoration"
                fill
                style={{ objectFit: 'cover', objectPosition: 'top right' }}
            />
        </div>
        <AppWrapper>
            <AuthWrapper>
                {children}</AuthWrapper>
        </AppWrapper>
        </body>
        </html>
    );
}
